<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="libi-PC" name="homeTestOnChrome" tests="1" failures="1" timestamp="15 Dec 2018 16:12:02 GMT" time="15.628" errors="0">
  <testcase name="@AfterClass CloseSession" time="0.0" classname="TestCasesHomeTest.Test1">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at UtilitesHomeTest.base.CloseSession(base.java:176)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- @AfterClass CloseSession -->
  <testcase name="@AfterTest doAfterTest" time="0.0" classname="TestCasesHomeTest.Test1">
    <skipped/>
  </testcase> <!-- @AfterTest doAfterTest -->
  <testcase name="test01_homeTestFlow" time="1.046" classname="TestCasesHomeTest.Test1">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at UtilitesHomeTest.base.takeSS(base.java:145)
	at UtilitesHomeTest.commonOps.clickOrChose(commonOps.java:55)
	at TestCasesHomeTest.Test1.test01_homeTestFlow(Test1.java:84)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- test01_homeTestFlow -->
</testsuite> <!-- homeTestOnChrome -->
